[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Richard's Development Tool"
edition = "2021"
homepage = "https://github.com/rcook/devtool"
keywords = ["general"]
license = "MIT"
name = "devtool"
repository = "https://github.com/rcook/devtool"
version = "0.0.22"

[dependencies]
anyhow = "1.0.71"
chrono = "0.4.26"
clap = { version = "4.3.11", features = ["derive"] }
colored = "2.0.4"
devtool-git = { path = "../devtool-git" }
devtool-version = { path = "../devtool-version" }
joatmon = "0.0.29"
lazy_static = "1.4.0"
log = { version = "0.4.19", features = ["std"] }
path-absolutize = "3.1.0"
rstest = "0.18.1"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
serde_yaml = "0.9.25"
thiserror = "1.0.43"
toml_edit = "0.19.12"
