[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Richard's Development Tool"
edition = "2021"
homepage = "https://github.com/rcook/devtool"
keywords = ["general"]
license = "MIT"
name = "devtool"
repository = "https://github.com/rcook/devtool"
version = "0.0.24"

[dependencies]
anyhow = "1.0.81"
chrono = "0.4.35"
clap = { version = "4.5.3", features = ["derive"] }
colored = "2.1.0"
devtool-git = { path = "../devtool-git" }
devtool-version = { path = "../devtool-version" }
joatmon = "0.0.30"
lazy_static = "1.4.0"
log = { version = "0.4.21", features = ["std"] }
path-absolutize = "3.1.1"
rstest = "0.18.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.33"
thiserror = "1.0.58"
toml_edit = "0.19.15"
