[package]
authors = ["Richard Cook"]
description = "Richard's Development Tool"
edition = "2021"
homepage = "https://github.com/rcook/devtool"
license = "MIT"
name = "devtool"
version = "0.0.6"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.1", features = ["derive"] }
colored = "2.0.0"
path-absolutize = "3.0.14"
rstest = "0.17.0"
serde = { version = "1.0.160", features = ["derive"] }
swiss-army-knife = { version = "0.0.4", git = "https://github.com/rcook/swiss-army-knife-rs", tag = "v0.0.4" }
toml_edit = "0.19.8"
