[package]
authors = ["Richard Cook"]
description = "Richard's Development Tool"
edition = "2021"
homepage = "https://github.com/rcook/devtool"
license = "MIT"
name = "devtool"
version = "0.0.0"

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
colored = "2.0.0"
default-env = "0.1.1"
git-version = "0.3.5"
path-absolutize = "3.0.14"
rstest = "0.17.0"
toml = "0.7.3"
