[package]
authors = ["Richard Cook"]
categories = ["development-tools"]
description = "Richard's Development Tool - Version Support"
edition = "2021"
homepage = "https://github.com/rcook/devtool"
keywords = ["general"]
license = "MIT"
name = "devtool-version"
repository = "https://github.com/rcook/devtool"
version = "0.0.25"

[dependencies]
anyhow = "1.0.81"
serde = "1.0.204"
thiserror = "1.0.58"

[dev-dependencies]
rstest = "0.18.2"
